post:
  x-eov-operation-id: importCommunityPackage
  x-eov-operation-handler: v1/handlers/community-packages/community-packages.handler
  tags:
    - Community Packages
  summary: Import a community package
  description: Import a community package into your n8n instance.
  requestBody:
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            packageName:
              type: string
              description: Name of package to be installed
  responses:
    '200':
      description: Operation successful.
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '500':
      description: Internal server error.
